services:
  mongo:
    image: mongo:7
    container_name: rbac_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  server:
    build: ./server
    container_name: rbac_server
    ports:
      - "4000:4000"
    environment:
      MONGO_URI: mongodb://mongo:27017/rbac
      PORT: "4000"
      JWT_SECRET: "dev_secret_change_me"
    depends_on:
      - mongo
    volumes:
      - ./server:/app
    command: ["npm","run","start"]

  client:
    build: ./client
    container_name: rbac_client
    ports:
      - "5173:5173"
    depends_on:
      - server

volumes:
  mongo_data:
